matrix:
  include:
    - language: clojure
      script:
       - lein uberjar
    - language: node_js
      node_js:
        - stable
      before_script:
        - npm install
      script:
        - npm run test
        - npm run coverage
notifications:
  email:
    - garyb1@live.ie
    - asteed7@gmail.com